FROM python:3.7-alpine
LABEL maintainer="imlonghao"

ADD https://github.com/sivel/speedtest-cli/raw/681cdf20a5fe774ba3aefedd0cd88cbff5384439/speedtest.py /speedtest_cli.py

CMD ["python", "/speedtest_cli.py"]